enforce_secure_profile: false
server_connect_timeout: 5000
listeners:
- bind_local_address: true
  force_default_server: false
  forced_hosts:
    pvp.md-5.net: pvp
  host: 0.0.0.0:19132
  max_players: 1
  motd: '&1Another XCord server'
  ping_passthrough: false
  priorities:
  - auth
  proxy_protocol: false
  query_enabled: false
  query_port: 19132
  tab_list: GLOBAL_PING
  tab_size: 60
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - serverswitcher.switch
  - bungeecord.command.list
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: 1000
ip_forward: true
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: 674dda6f-eeab-42ea-bc24-2ebc579324f8
online_mode: false
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  auth:
    address: node.hindcraft.fun:19121
    motd: '           &x&F&F&0&0&1&B&lH&x&F&F&0&E&1&9&lI&x&F&F&1&D&1&7&lN&x&F&F&2&B&1&6&lD&x&F&F&3&A&1&4&lC&x&F&F&4&8&1&2&lR&x&F&F&5&7&1&0&lA&x&F&F&6&5&0&E&lF&x&F&F&7&4&0&D&lT
      &x&F&F&8&2&0&B&lN&x&F&F&9&1&0&9&lE&x&F&F&9&F&0&7&lT&x&F&F&A&E&0&5&lW&x&F&F&B&C&0&4&lO&x&F&F&C&B&0&2&lR&x&F&F&D&9&0&0&lK    &c&l1.8
      - 1.20&r           &x&F&F&0&0&1&B&lʟ&x&E&4&0&2&3&3&lɪ&x&C&9&0&4&4&B&lꜰ&x&A&E&0&5&6&3&lᴇ&x&9&4&0&7&7&B&lꜱ&x&7&9&0&9&9&3&lᴛ&x&5&E&0&B&A&B&lᴇ&x&4&3&0&D&C&3&lᴀ&x&2&8&0&E&D&B&lʟ   &x&0&D&1&0&F&3&l-   &x&0&6&1&1&F&9&lꜰ&x&1&1&1&1&E&E&lꜰ&x&1&C&1&0&E&3&lᴀ   &x&2&7&1&0&D&8&l-   &x&3&2&1&0&C&C&lʙ&x&3&D&0&F&C&1&lᴏ&x&4&8&0&F&B&6&lx&x&5&3&0&F&A&B&lᴘ&x&5&E&0&E&9&F&lᴠ&x&6&9&0&E&9&4&lᴘ'
    restricted: false
  bedwars:
    address: node.hindcraft.fun:19127
    motd: '&1Just'
    restricted: false
  events:
    address: node.hindcraft.fun:19126
    motd: '&1Just'
    restricted: false
  ffa:
    address: node.hindcraft.fun:19123
    motd: '&1Just'
    restricted: false
  hub:
    address: node.hindcraft.fun:19131
    motd: '&1Just'
    restricted: false
  lifesteal:
    address: node.hindcraft.fun:19120
    motd: '&1Just'
    restricted: false
